server:
  port: 8080
  servlet:
    context-path: /utils

spring:
  application:
    name: utils-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wmh.utils.demo.entity
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    com.wmhou.admin.mapper: DEBUG
